name: restaurant_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  shimmer: ^3.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.3.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  intl: ^0.20.2
  sqflite: ^2.3.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700

  assets:
  - assets/loading.json
  - assets/fonts/
  - assets/images/

  uses-material-design: true
